# -*- coding: utf-8 -*-
"""0518_delete.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fhfvqebfXK-CIBtiXi85XA87mhlut5Kq
"""


import nltk

from nltk.tokenize import word_tokenize

#id 위치 확인
def se_find_id(any_list):
    re = 'NAN'
    for i in range(0,len(any_list)):
        if(any_list[i] == 'id'):
            re = any_list[i+1]

    return re

#error 확인
def error_msg(se_sql):
    re = 'normal'
    if 'NAN' in se_sql:
        re = 'error'
    
    return re

# id N번 제품 삭제해줘.
# error나면 "error"라고 리턴합니다!
def delete_func(some_list):
    cart_id = se_find_id(some_list)  
    
    sql = "DELETE FROM cart WHERE cart_id = " + cart_id
    error_check = error_msg(sql)
    
    if (error_check == 'error'):
        return error_check
    else:
        return sql