# -*- coding: utf-8 -*-
"""0518_insert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Org2i21Ry55Y5QrI96CXUN7cChFkQHwY
"""


import nltk
from nltk.tokenize import word_tokenize

def se_find_quantity(any_list):
    re = 'NAN'
    for i in range(0, len(any_list)):
        if(any_list[i].isdigit() == True):
            re = any_list[i]
    
    return re

#error 확인
def error_msg(se_sql):
    re = 'normal'
    if 'NAN' in se_sql:
        re = 'error'
    
    return re

def insert_func(some_list, id_one):
    quantity_dic = {'one' : '1', 'two': '2', 'three' : '3', 'four' : '4', 'five' : '5'}
    some_list 
    quantity_value = 0
    list_key = list(quantity_dic.keys()) #key값만 담은 리스트 
    # str_p = ['three', 'product']
    for str in some_list:
        for key in list_key:
            if str == key:
                quantity_value = quantity_dic[key]
                break



    id_value = id_one
    first_sql = "INSERT INTO cart (id, product_name, price) SELECT id, product_name, price FROM product WHERE id = '" + id_value + "'"
    second_sql = "UPDATE cart SET quantity = " + quantity_value + " WHERE id = '" + id_value + "'"
    #second_sql = "INSERT INTO cart(quantity) VALUES(" + quantity_value +") WHERE id = '" + id_value + "'"
    
    error_check = error_msg(second_sql) 
    if (error_check == 'error'):
        return error_check
    else:
        return first_sql, second_sql, quantity_value  